name: 'Commit Message Check'

on: push

jobs:
  check-commit-message:
    name: Check Commit Message
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Commit Message
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(FEAT|FIX|BUILD|CI|DOCS|PERF|REFACTOR|REVERT|STYLE|TEST) : *'
          flags: 'gm'
          error: 'Your commit message should be like this : (FEAT|FIX|BUILD|CI|DOCS|PERF|REFACTOR|REVERT|STYLE|TEST) : *'
